# --- quri_parts/circuit/circuit_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const circuit_classes = [
    :ImmutableQuantumCircuit,
    :MutableQuantumCircuitProtocol,
    :NonParametricQuantumCircuit,
    :QuantumCircuit,
    :QuantumCircuitProtocol,
]
