# --- quri_parts/circuit/circuit_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const circuit_alias_classes = [
    :ParametricQuantumGate => "quri_parts.circuit.gate",
    :QuantumGate => "quri_parts.circuit.gate",
]
