# --- quri_parts/core/state/state_vector_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst state_vector_alias_classes = [
    :CircuitQuantumStateMixin => "quri_parts.core.state.state",
    :NonParametricQuantumCircuit => "quri_parts.circuit.circuit",
    :QuantumState => "quri_parts.core.state.state",
]
