# --- quri_parts/core/state/state_vector_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst state_vector_alias_functions = [
    :readonly_array => "quri_parts.core.utils.array",
]
