version: '3'
services:
  jupyter:
    image: kyurijl
    container_name: kyurijl-jupyter
    volumes:
      - ./:/workspace/Kyuri.jl
    working_dir: /workspace/Kyuri.jl
    ports:
      - "8888:8888"
    command: jupyter notebook --notebook-dir /workspace/Kyuri.jl --ip=0.0.0.0 --allow-root
  lab:
    image: kyurijl
    container_name: kyurijl-lab
    volumes:
      - ./:/workspace/Kyuri.jl
    working_dir: /workspace/Kyuri.jl
    ports:
      - "8888:8888"
    command: jupyter lab --notebook-dir /workspace/Kyuri.jl --ip=0.0.0.0 --allow-root
  julia:
    image: kyurijl
    container_name: kyurijl-julia
    volumes:
      - ./:/workspace/Kyuri.jl
    working_dir: /workspace/Kyuri.jl
    command: julia --project=/workspace/Kyuri.jl
  shell:
    image: kyurijl
    container_name: kyurijl-shell
    volumes:
      - ./:/workspace/Kyuri.jl
    working_dir: /workspace/Kyuri.jl
    command: /bin/bash
  web:
    image: kyurijl
    container_name: kyurijl-packagedocs
    volumes:
      - ./:/workspace/Kyuri.jl
    working_dir: /workspace/Kyuri.jl
    ports:
      - "8000:8000"
    command: make web
  pluto:
    image: kyurijl
    container_name: kyurijl-pluto
    volumes:
      - ./:/workspace/Kyuri.jl
    working_dir: /workspace/Kyuri.jl
    ports:
      - "1234:1234"
    command: julia -e 'import Pluto; Pluto.run(host="0.0.0.0", port=1234)'
