# --- quri_parts/core/operator/grouping/pauli_grouping_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const pauli_grouping_alias_classes = [
    :BinarySymplecticVector => "quri_parts.core.operator.representation.bsf",
    :Operator => "quri_parts.core.operator.operator",
    :PauliLabel => "quri_parts.core.operator.pauli",
    :SinglePauli => "quri_parts.core.operator.pauli",
]
