# --- quri_parts/core/operator/grouping/pauli_grouping_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const pauli_grouping_alias_functions = [
    :bsv_bitwise_commute => "quri_parts.core.operator.representation.bsf",
    :pauli_label_to_bsv => "quri_parts.core.operator.representation.bsf",
]
