# --- quri_parts/core/state/state_vector_parametric_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst state_vector_parametric_alias_classes = [
    :ParametricCircuitQuantumStateMixin => "quri_parts.core.state.state_parametric",
    :QuantumState => "quri_parts.core.state.state",
    :QuantumStateVector => "quri_parts.core.state.state_vector",
    :QuantumStateVectorMixin => "quri_parts.core.state.state_vector",
    :UnboundParametricQuantumCircuitProtocol => "quri_parts.circuit.circuit_parametric",
]
