# --- quri_parts/core/state/state_vector_parametric_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const state_vector_parametric_classes = [
    :ParametricQuantumStateVector,
]
