# --- quri_parts/core/state_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const state_alias_functions = [
    :comp_basis_superposition => "quri_parts.core.state.comp_basis",
]
