# --- quri_parts/core/state/state_parametric_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst state_parametric_alias_classes = [
    :GeneralCircuitQuantumState => "quri_parts.core.state.state",
    :QuantumState => "quri_parts.core.state.state",
    :UnboundParametricQuantumCircuitProtocol => "quri_parts.circuit.circuit_parametric",
]
