# --- quri_parts/core/measurement_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const measurement_alias_classes = [
    :CommutablePauliSetMeasurement => "quri_parts.core.measurement.interface",
    :CommutablePauliSetMeasurementTuple => "quri_parts.core.measurement.interface",
]
