# --- quri_parts/core/measurement_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const measurement_alias_functions = [
    :bitwise_commuting_pauli_measurement => "quri_parts.core.measurement.bitwise_commuting_pauli",
    :bitwise_commuting_pauli_measurement_circuit => "quri_parts.core.measurement.bitwise_commuting_pauli",
    :bitwise_pauli_reconstructor_factory => "quri_parts.core.measurement.bitwise_commuting_pauli",
    :individual_pauli_measurement => "quri_parts.core.measurement.bitwise_commuting_pauli",
]
