# --- quri_parts/core/state/state_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst state_alias_classes = [
    :ImmutableQuantumCircuit => "quri_parts.circuit.circuit",
    :NonParametricQuantumCircuit => "quri_parts.circuit.circuit",
    :QuantumCircuit => "quri_parts.circuit.circuit",
]
