# --- quri_parts/core/operator/operator_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const operator_alias_functions = [
    :pauli_product => "quri_parts.core.operator.pauli",
]
