# --- quri_parts/core/estimator/sampling/estimator_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const estimator_alias_classes = [
    :CircuitQuantumState => "quri_parts.core.state.state",
    :Estimate => "quri_parts.core.estimator",
    :Operator => "quri_parts.core.operator.operator",
]
