# --- quri_parts/core/estimator/sampling/estimator_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const estimator_alias_functions = [
    :general_pauli_sum_expectation_estimator => "quri_parts.core.estimator.sampling.pauli",
    :general_pauli_sum_sample_variance => "quri_parts.core.estimator.sampling.pauli",
]
