# --- quri_parts/core/measurement/interface_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const interface_alias_classes = [
    :Operator => "quri_parts.core.operator.operator",
    :PauliLabel => "quri_parts.core.operator.pauli",
    :QuantumGate => "quri_parts.circuit.gate",
]
