# --- quri_parts/core/state/comp_basis_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst comp_basis_alias_functions = [
    :different_bit_index => "quri_parts.core.utils.bit",
    :get_bit => "quri_parts.core.utils.bit",
    :is_pauli_name => "quri_parts.circuit.gate_names",
]
