# --- quri_parts/core/state/comp_basis_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const comp_basis_alias_classes = [
    :CircuitQuantumState => "quri_parts.core.state.state",
    :GeneralCircuitQuantumState => "quri_parts.core.state.state",
    :ImmutableQuantumCircuit => "quri_parts.circuit.circuit",
    :NonParametricQuantumCircuit => "quri_parts.circuit.circuit",
    :QuantumCircuit => "quri_parts.circuit.circuit",
    :QuantumGate => "quri_parts.circuit.gate",
]
