# --- quri_parts/circuit/parameter_mapping_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst parameter_mapping_alias_classes = [
    :Parameter => "quri_parts.circuit.circuit_parametric",
]
