# --- quri_parts/circuit_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const circuit_alias_functions = [
    :inverse_gate => "quri_parts.circuit.inverse_gate",
    :is_clifford => "quri_parts.circuit.clifford_gate",
]
