# --- quri_parts/circuit/gate_names_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst gate_names_functions = [
    :is_gate_name,
    :is_multi_qubit_gate_name,
    :is_parametric_gate_name,
    :is_pauli_name,
    :is_single_qubit_gate_name,
    :is_two_qubit_gate_name,
]
