# --- quri_parts/core/operator/representation/bsf_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const bsf_alias_classes = [
    :PauliLabel => "quri_parts.core.operator.pauli",
    :SinglePauli => "quri_parts.core.operator.pauli",
]
