# --- quri_parts/backend_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst backend_alias_classes = [
    :NonParametricQuantumCircuit => "quri_parts.circuit.circuit",
]
