# --- quri_parts/backend_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst backend_classes = [
    :BackendError,
    :CompositeSamplingJob,
    :CompositeSamplingResult,
    :SamplingBackend,
    :SamplingJob,
    :SamplingResult,
]
