# --- quri_parts/core/operator_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst operator_alias_classes = [
    :Operator => "quri_parts.core.operator.operator",
    :PauliLabel => "quri_parts.core.operator.pauli",
    :SinglePauli => "quri_parts.core.operator.pauli",
]
