# --- quri_parts/core/operator_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst operator_alias_functions = [
    :commutator => "quri_parts.core.operator.operator",
    :pauli_label => "quri_parts.core.operator.pauli",
    :pauli_name => "quri_parts.core.operator.pauli",
    :pauli_product => "quri_parts.core.operator.pauli",
    :transition_amp_comp_basis => "quri_parts.core.operator.representation",
    :transition_amp_representation => "quri_parts.core.operator.representation",
    :trotter_suzuki_decomposition => "quri_parts.core.operator.trotter_suzuki",
    :zero => "quri_parts.core.operator.operator",
]
