# --- quri_parts/core/measurement/bitwise_commuting_pauli_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst bitwise_commuting_pauli_alias_functions = [
    :bitwise_pauli_grouping => "quri_parts.core.operator.grouping.pauli_grouping",
    :individual_pauli_grouping => "quri_parts.core.operator.grouping.pauli_grouping",
    :parity_sign_of_bits => "quri_parts.core.utils.bit",
    :pauli_label_to_bsv => "quri_parts.core.operator.representation.bsf",
]
