# --- quri_parts/core/operator/representation_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const representation_functions = [
    :transition_amp_comp_basis,
    :transition_amp_representation,
]
