# --- quri_parts/core/operator/representation_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const representation_alias_classes = [
    :BinarySymplecticVector => "quri_parts.core.operator.representation.bsf",
]
