# --- quri_parts/core/operator/representation_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const representation_alias_functions = [
    :bsv_bitwise_commute => "quri_parts.core.operator.representation.bsf",
    :parity_sign_of_bits => "quri_parts.core.utils.bit",
    :pauli_label_to_bsv => "quri_parts.core.operator.representation.bsf",
]
