# --- quri_parts/core/operator/grouping_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst grouping_alias_functions = [
    :bitwise_pauli_grouping => "quri_parts.core.operator.grouping.pauli_grouping",
    :individual_pauli_grouping => "quri_parts.core.operator.grouping.pauli_grouping",
    :sorted_injection_grouping => "quri_parts.core.operator.grouping.pauli_grouping",
]
