# --- quri_parts/core/estimator/sampling/pauli_alias_functions.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const pauli_alias_functions = [
    :bitwise_pauli_reconstructor_factory => "quri_parts.core.measurement.bitwise_commuting_pauli",
    :count_var => "quri_parts.core.utils.statistics",
]
