# --- quri_parts/core/estimator/sampling/pauli_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_api
const pauli_alias_classes = [
    :PauliLabel => "quri_parts.core.operator.pauli",
]
