# --- quri_parts/core/sampling_alias_classes.jl
# This file is generated by quri_parts_api_list.write_pymod_apiconst sampling_alias_classes = [
    :NonParametricQuantumCircuit => "quri_parts.circuit.circuit",
    :Operator => "quri_parts.core.operator.operator",
    :SamplingBackend => "quri_parts.backend",
]
